### ISSUE TITLE
Alignmnt issue

### ISSUE THREAD

**Issue by Ayshathulnihala** [mohammedek/homemade_loc_tracking_app#11]
In first page there is a alignment issue in
'Sign in using f G
![Screenshot_20230125-113618.jpg](https://user-images.githubusercontent.com/118208691/214520883-833585cb-c2c5-4dbc-8e16-81d1656c20a9.jpg)

![IMG-20230125-WA0110.jpg](https://user-images.githubusercontent.com/118208691/214520922-02a4d2e4-8f9b-4704-a59d-ee004d3a6b2e.jpg)

**Comment by mohammedek** [comment]
When given  size  as  in figma, page will have scroll view, because of that every widget height property is reduced by 3 or 2 px
